version: '3.8'
services:

  movies-admin:
    build:
      context: ./movies_admin
      dockerfile: Dockerfile
    expose:
      - "8000"
    env_file:
      - ./.env
    depends_on:
      theatre-db:
        condition: service_healthy
    volumes:
      - static_volume:/opt/app/static/

  etl:
    build:
      context: ./etl_service
      dockerfile: Dockerfile
    env_file:
      - ./.env
    depends_on:
      theatre-db:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

  fastapi:
    build:
      context: ./fast_api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    expose:
      - "8000"
    env_file:
      - ./.env
    depends_on:
      theatre-db:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      redis:
        condition: service_healthy

  nginx:
    image: nginx:1.27.4
    volumes:
      - ./configs/nginx:/etc/nginx/conf.d:ro
      - static_volume:/opt/app/static/
    depends_on:
      - fastapi
    ports:
      - "80:80"

  theatre-db:
    image: postgres:17.4
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./database_dump.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - "${POSTGRES_PORT}"
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  elasticsearch:
    image: elasticsearch:8.6.2
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    expose:
      - "${ELASTIC_PORT}"
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms200m -Xmx200m"
    healthcheck:
      test: ["CMD", "curl", "-s", "http://localhost:9200"]
      interval: 10s
      timeout: 10s
      retries: 15

  redis:
    image: redis:7.4.3
    volumes:
      - redis-data:/data
      - ./configs/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    expose:
      - "${REDIS_PORT}"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 10s
      retries: 15

volumes:
  pg-data:
  elastic-data:
  redis-data:
  static_volume:
