# coding: utf-8

"""
    Movie theater

    Информация о фильмах, жанрах и людях, участвовавших в создании произведения

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from openapi_client.models.genre import Genre
from openapi_client.models.person import Person
from typing import Optional, Set
from typing_extensions import Self

class FilmFullResponse(BaseModel):
    """
    Полная информация по кинопроизведениям
    """ # noqa: E501
    uuid: StrictStr = Field(description="Уникальный идентификатор фильма")
    title: Annotated[str, Field(strict=True, max_length=255)] = Field(description="Название кинопроизведения")
    imdb_rating: Optional[Union[Annotated[float, Field(le=10.0, strict=True, ge=0.0)], Annotated[int, Field(le=10, strict=True, ge=0)]]] = None
    genres: Optional[List[Genre]] = None
    description: Optional[Annotated[str, Field(strict=True, max_length=2000)]] = None
    pg_rating: Optional[Annotated[str, Field(strict=True, max_length=10)]] = None
    duration: Optional[StrictInt] = None
    release_year: Optional[Annotated[int, Field(le=2030, strict=True, ge=1888)]] = None
    poster_url: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=2083)]] = None
    actors: Optional[List[Person]] = None
    writers: Optional[List[Person]] = None
    directors: Optional[List[Person]] = None
    __properties: ClassVar[List[str]] = ["uuid", "title", "imdb_rating", "genres", "description", "pg_rating", "duration", "release_year", "poster_url", "actors", "writers", "directors"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FilmFullResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in genres (list)
        _items = []
        if self.genres:
            for _item_genres in self.genres:
                if _item_genres:
                    _items.append(_item_genres.to_dict())
            _dict['genres'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in actors (list)
        _items = []
        if self.actors:
            for _item_actors in self.actors:
                if _item_actors:
                    _items.append(_item_actors.to_dict())
            _dict['actors'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in writers (list)
        _items = []
        if self.writers:
            for _item_writers in self.writers:
                if _item_writers:
                    _items.append(_item_writers.to_dict())
            _dict['writers'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in directors (list)
        _items = []
        if self.directors:
            for _item_directors in self.directors:
                if _item_directors:
                    _items.append(_item_directors.to_dict())
            _dict['directors'] = _items
        # set to None if imdb_rating (nullable) is None
        # and model_fields_set contains the field
        if self.imdb_rating is None and "imdb_rating" in self.model_fields_set:
            _dict['imdb_rating'] = None

        # set to None if genres (nullable) is None
        # and model_fields_set contains the field
        if self.genres is None and "genres" in self.model_fields_set:
            _dict['genres'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if pg_rating (nullable) is None
        # and model_fields_set contains the field
        if self.pg_rating is None and "pg_rating" in self.model_fields_set:
            _dict['pg_rating'] = None

        # set to None if duration (nullable) is None
        # and model_fields_set contains the field
        if self.duration is None and "duration" in self.model_fields_set:
            _dict['duration'] = None

        # set to None if release_year (nullable) is None
        # and model_fields_set contains the field
        if self.release_year is None and "release_year" in self.model_fields_set:
            _dict['release_year'] = None

        # set to None if poster_url (nullable) is None
        # and model_fields_set contains the field
        if self.poster_url is None and "poster_url" in self.model_fields_set:
            _dict['poster_url'] = None

        # set to None if actors (nullable) is None
        # and model_fields_set contains the field
        if self.actors is None and "actors" in self.model_fields_set:
            _dict['actors'] = None

        # set to None if writers (nullable) is None
        # and model_fields_set contains the field
        if self.writers is None and "writers" in self.model_fields_set:
            _dict['writers'] = None

        # set to None if directors (nullable) is None
        # and model_fields_set contains the field
        if self.directors is None and "directors" in self.model_fields_set:
            _dict['directors'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FilmFullResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "uuid": obj.get("uuid"),
            "title": obj.get("title"),
            "imdb_rating": obj.get("imdb_rating"),
            "genres": [Genre.from_dict(_item) for _item in obj["genres"]] if obj.get("genres") is not None else None,
            "description": obj.get("description"),
            "pg_rating": obj.get("pg_rating"),
            "duration": obj.get("duration"),
            "release_year": obj.get("release_year"),
            "poster_url": obj.get("poster_url"),
            "actors": [Person.from_dict(_item) for _item in obj["actors"]] if obj.get("actors") is not None else None,
            "writers": [Person.from_dict(_item) for _item in obj["writers"]] if obj.get("writers") is not None else None,
            "directors": [Person.from_dict(_item) for _item in obj["directors"]] if obj.get("directors") is not None else None
        })
        return _obj


