# coding: utf-8

"""
    Movie theater

    Информация о фильмах, жанрах и людях, участвовавших в создании произведения

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.film_base_response import FilmBaseResponse

class TestFilmBaseResponse(unittest.TestCase):
    """FilmBaseResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FilmBaseResponse:
        """Test FilmBaseResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FilmBaseResponse`
        """
        model = FilmBaseResponse()
        if include_optional:
            return FilmBaseResponse(
                uuid = '3d825f60-9fff-4dfe-b294-1a45fa1e115d',
                title = 'Star Wars: Episode IV - A New Hope'
            )
        else:
            return FilmBaseResponse(
                uuid = '3d825f60-9fff-4dfe-b294-1a45fa1e115d',
                title = 'Star Wars: Episode IV - A New Hope',
        )
        """

    def testFilmBaseResponse(self):
        """Test FilmBaseResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
