# coding: utf-8

"""
    Movie theater

    Информация о фильмах, жанрах и людях, участвовавших в создании произведения

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_film_details_api_v1_films_film_id_get(self) -> None:
        """Test case for film_details_api_v1_films_film_id_get

        Получить информацию о кинопроизведении
        """
        pass

    def test_genre_details_api_v1_genres_genre_id_get(self) -> None:
        """Test case for genre_details_api_v1_genres_genre_id_get

        Получить информацию о жанре
        """
        pass

    def test_list_films_api_v1_films_get(self) -> None:
        """Test case for list_films_api_v1_films_get

        Получить список фильмов по заданным критериям
        """
        pass

    def test_list_films_api_v1_persons_person_id_films_get(self) -> None:
        """Test case for list_films_api_v1_persons_person_id_films_get

        Получить список фильмов персоны
        """
        pass

    def test_list_genres_api_v1_genres_get(self) -> None:
        """Test case for list_genres_api_v1_genres_get

        Получить список жанров
        """
        pass

    def test_person_details_api_v1_persons_person_id_get(self) -> None:
        """Test case for person_details_api_v1_persons_person_id_get

        Получить информацию о персоне
        """
        pass

    def test_search_films_api_v1_films_search_get(self) -> None:
        """Test case for search_films_api_v1_films_search_get

        Поиск кинопроизведений
        """
        pass

    def test_search_films_api_v1_persons_search_get(self) -> None:
        """Test case for search_films_api_v1_persons_search_get

        Поиск персон
        """
        pass


if __name__ == '__main__':
    unittest.main()
