# coding: utf-8

"""
    Movie theater

    Информация о фильмах, жанрах и людях, участвовавших в создании произведения

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.film_short_response import FilmShortResponse

class TestFilmShortResponse(unittest.TestCase):
    """FilmShortResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FilmShortResponse:
        """Test FilmShortResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FilmShortResponse`
        """
        model = FilmShortResponse()
        if include_optional:
            return FilmShortResponse(
                uuid = '3d825f60-9fff-4dfe-b294-1a45fa1e115d',
                title = 'Star Wars: Episode IV - A New Hope',
                imdb_rating = 0.0,
                genres = [
                    openapi_client.models.genre.Genre(
                        uuid = '3d8d9bf5-0d90-4353-88ba-4ccc5d2c07ff', 
                        name = 'Action', 
                        description = '', )
                    ]
            )
        else:
            return FilmShortResponse(
                uuid = '3d825f60-9fff-4dfe-b294-1a45fa1e115d',
                title = 'Star Wars: Episode IV - A New Hope',
        )
        """

    def testFilmShortResponse(self):
        """Test FilmShortResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
