# coding: utf-8

"""
    Movie theater

    Информация о фильмах, жанрах и людях, участвовавших в создании произведения

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.film_full_response import FilmFullResponse

class TestFilmFullResponse(unittest.TestCase):
    """FilmFullResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FilmFullResponse:
        """Test FilmFullResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FilmFullResponse`
        """
        model = FilmFullResponse()
        if include_optional:
            return FilmFullResponse(
                uuid = '3d825f60-9fff-4dfe-b294-1a45fa1e115d',
                title = 'Star Wars: Episode IV - A New Hope',
                imdb_rating = 0.0,
                genres = [
                    openapi_client.models.genre.Genre(
                        uuid = '3d8d9bf5-0d90-4353-88ba-4ccc5d2c07ff', 
                        name = 'Action', 
                        description = '', )
                    ],
                description = '',
                pg_rating = '',
                duration = 56,
                release_year = 1888.0,
                poster_url = '0',
                actors = [
                    openapi_client.models.person.Person(
                        uuid = '5b4bf1bc-3397-4e83-9b17-8b10c6544ed1', 
                        full_name = 'George Lucas', )
                    ],
                writers = [
                    openapi_client.models.person.Person(
                        uuid = '5b4bf1bc-3397-4e83-9b17-8b10c6544ed1', 
                        full_name = 'George Lucas', )
                    ],
                directors = [
                    openapi_client.models.person.Person(
                        uuid = '5b4bf1bc-3397-4e83-9b17-8b10c6544ed1', 
                        full_name = 'George Lucas', )
                    ]
            )
        else:
            return FilmFullResponse(
                uuid = '3d825f60-9fff-4dfe-b294-1a45fa1e115d',
                title = 'Star Wars: Episode IV - A New Hope',
        )
        """

    def testFilmFullResponse(self):
        """Test FilmFullResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
