# coding: utf-8

"""
    Movie theater

    Информация о фильмах, жанрах и людях, участвовавших в создании произведения

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.person_full_response import PersonFullResponse

class TestPersonFullResponse(unittest.TestCase):
    """PersonFullResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PersonFullResponse:
        """Test PersonFullResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PersonFullResponse`
        """
        model = PersonFullResponse()
        if include_optional:
            return PersonFullResponse(
                uuid = '5b4bf1bc-3397-4e83-9b17-8b10c6544ed1',
                full_name = 'George Lucas',
                films = [
                    null
                    ]
            )
        else:
            return PersonFullResponse(
                uuid = '5b4bf1bc-3397-4e83-9b17-8b10c6544ed1',
                full_name = 'George Lucas',
        )
        """

    def testPersonFullResponse(self):
        """Test PersonFullResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
