# coding: utf-8

"""
    Movie theater

    Информация о фильмах, жанрах и людях, участвовавших в создании произведения

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.person import Person

class TestPerson(unittest.TestCase):
    """Person unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Person:
        """Test Person
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Person`
        """
        model = Person()
        if include_optional:
            return Person(
                uuid = '5b4bf1bc-3397-4e83-9b17-8b10c6544ed1',
                full_name = 'George Lucas'
            )
        else:
            return Person(
                uuid = '5b4bf1bc-3397-4e83-9b17-8b10c6544ed1',
                full_name = 'George Lucas',
        )
        """

    def testPerson(self):
        """Test Person"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
