# coding: utf-8

"""
    Movie theater

    Информация о фильмах, жанрах и людях, участвовавших в создании произведения

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.genre import Genre

class TestGenre(unittest.TestCase):
    """Genre unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Genre:
        """Test Genre
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Genre`
        """
        model = Genre()
        if include_optional:
            return Genre(
                uuid = '3d8d9bf5-0d90-4353-88ba-4ccc5d2c07ff',
                name = 'Action',
                description = ''
            )
        else:
            return Genre(
                uuid = '3d8d9bf5-0d90-4353-88ba-4ccc5d2c07ff',
                name = 'Action',
        )
        """

    def testGenre(self):
        """Test Genre"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
