/* tslint:disable */
/* eslint-disable */
/**
 * Movie theater
 * Информация о фильмах, жанрах и людях, участвовавших в создании произведения
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * Базовая информация по кинопроизведениям
 * @export
 * @interface FilmBaseResponse
 */
export interface FilmBaseResponse {
    /**
     * Уникальный идентификатор фильма
     * @type {string}
     * @memberof FilmBaseResponse
     */
    'uuid': string;
    /**
     * Название кинопроизведения
     * @type {string}
     * @memberof FilmBaseResponse
     */
    'title': string;
}
/**
 * Полная информация по кинопроизведениям
 * @export
 * @interface FilmFullResponse
 */
export interface FilmFullResponse {
    /**
     * Уникальный идентификатор фильма
     * @type {string}
     * @memberof FilmFullResponse
     */
    'uuid': string;
    /**
     * Название кинопроизведения
     * @type {string}
     * @memberof FilmFullResponse
     */
    'title': string;
    /**
     * 
     * @type {number}
     * @memberof FilmFullResponse
     */
    'imdb_rating'?: number | null;
    /**
     * 
     * @type {Array<Genre>}
     * @memberof FilmFullResponse
     */
    'genres'?: Array<Genre> | null;
    /**
     * 
     * @type {string}
     * @memberof FilmFullResponse
     */
    'description'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FilmFullResponse
     */
    'pg_rating'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof FilmFullResponse
     */
    'duration'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof FilmFullResponse
     */
    'release_year'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof FilmFullResponse
     */
    'poster_url'?: string | null;
    /**
     * 
     * @type {Array<Person>}
     * @memberof FilmFullResponse
     */
    'actors'?: Array<Person> | null;
    /**
     * 
     * @type {Array<Person>}
     * @memberof FilmFullResponse
     */
    'writers'?: Array<Person> | null;
    /**
     * 
     * @type {Array<Person>}
     * @memberof FilmFullResponse
     */
    'directors'?: Array<Person> | null;
}
/**
 * Короткая информация по кинопроизведениям
 * @export
 * @interface FilmShortResponse
 */
export interface FilmShortResponse {
    /**
     * Уникальный идентификатор фильма
     * @type {string}
     * @memberof FilmShortResponse
     */
    'uuid': string;
    /**
     * Название кинопроизведения
     * @type {string}
     * @memberof FilmShortResponse
     */
    'title': string;
    /**
     * 
     * @type {number}
     * @memberof FilmShortResponse
     */
    'imdb_rating'?: number | null;
    /**
     * 
     * @type {Array<Genre>}
     * @memberof FilmShortResponse
     */
    'genres'?: Array<Genre> | null;
}
/**
 * Модель жанра фильма
 * @export
 * @interface Genre
 */
export interface Genre {
    /**
     * Уникальный идентификатор жанра
     * @type {string}
     * @memberof Genre
     */
    'uuid': string;
    /**
     * Название жанра
     * @type {string}
     * @memberof Genre
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof Genre
     */
    'description'?: string | null;
}
/**
 * 
 * @export
 * @interface HTTPValidationError
 */
export interface HTTPValidationError {
    /**
     * 
     * @type {Array<ValidationError>}
     * @memberof HTTPValidationError
     */
    'detail'?: Array<ValidationError>;
}
/**
 * Модель персоны (актёра, режиссёра, сценариста)
 * @export
 * @interface Person
 */
export interface Person {
    /**
     * Уникальный идентификатор персоны
     * @type {string}
     * @memberof Person
     */
    'uuid': string;
    /**
     * Полное имя персоны
     * @type {string}
     * @memberof Person
     */
    'full_name': string;
}
/**
 * Модель фильмов с рейтингом
 * @export
 * @interface PersonFilms
 */
export interface PersonFilms {
    /**
     * Уникальный идентификатор фильма
     * @type {string}
     * @memberof PersonFilms
     */
    'uuid': string;
    /**
     * Название кинопроизведения
     * @type {string}
     * @memberof PersonFilms
     */
    'title': string;
    /**
     * 
     * @type {number}
     * @memberof PersonFilms
     */
    'imdb_rating'?: number | null;
}
/**
 * Полная информация по персоне
 * @export
 * @interface PersonFullResponse
 */
export interface PersonFullResponse {
    /**
     * Уникальный идентификатор персоны
     * @type {string}
     * @memberof PersonFullResponse
     */
    'uuid': string;
    /**
     * Полное имя персоны
     * @type {string}
     * @memberof PersonFullResponse
     */
    'full_name': string;
    /**
     * 
     * @type {Array<any>}
     * @memberof PersonFullResponse
     */
    'films'?: Array<any> | null;
}
/**
 * 
 * @export
 * @interface ValidationError
 */
export interface ValidationError {
    /**
     * 
     * @type {Array<ValidationErrorLocInner>}
     * @memberof ValidationError
     */
    'loc': Array<ValidationErrorLocInner>;
    /**
     * 
     * @type {string}
     * @memberof ValidationError
     */
    'msg': string;
    /**
     * 
     * @type {string}
     * @memberof ValidationError
     */
    'type': string;
}
/**
 * 
 * @export
 * @interface ValidationErrorLocInner
 */
export interface ValidationErrorLocInner {
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Возвращает полную информацию о кинопроизведении по его идентификатору
         * @summary Получить информацию о кинопроизведении
         * @param {string} filmId UUID фильма
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        filmDetailsApiV1FilmsFilmIdGet: async (filmId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'filmId' is not null or undefined
            assertParamExists('filmDetailsApiV1FilmsFilmIdGet', 'filmId', filmId)
            const localVarPath = `/api/v1/films/{film_id}`
                .replace(`{${"film_id"}}`, encodeURIComponent(String(filmId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Возвращает полную информацию о жанре по его идентификатору
         * @summary Получить информацию о жанре
         * @param {string} genreId UUID жанра
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        genreDetailsApiV1GenresGenreIdGet: async (genreId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'genreId' is not null or undefined
            assertParamExists('genreDetailsApiV1GenresGenreIdGet', 'genreId', genreId)
            const localVarPath = `/api/v1/genres/{genre_id}`
                .replace(`{${"genre_id"}}`, encodeURIComponent(String(genreId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Возвращает список из короткой информации по кинопроизведениям по заданным фильтрам
         * @summary Получить список фильмов по заданным критериям
         * @param {string} [sort] Сортировка (-imdb_rating для DESC, imdb_rating для ASC)
         * @param {string | null} [genre] UUID жанра для фильтрации
         * @param {number} [page] Номер страницы
         * @param {number} [size] Количество элементов на странице (1-100)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listFilmsApiV1FilmsGet: async (sort?: string, genre?: string | null, page?: number, size?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/films/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (sort !== undefined) {
                localVarQueryParameter['sort'] = sort;
            }

            if (genre !== undefined) {
                localVarQueryParameter['genre'] = genre;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Возвращает список из короткой информации по кинопроизведениям персоны
         * @summary Получить список фильмов персоны
         * @param {string} personId UUID персоны
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listFilmsApiV1PersonsPersonIdFilmsGet: async (personId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'personId' is not null or undefined
            assertParamExists('listFilmsApiV1PersonsPersonIdFilmsGet', 'personId', personId)
            const localVarPath = `/api/v1/persons/{person_id}/films`
                .replace(`{${"person_id"}}`, encodeURIComponent(String(personId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Возвращает список жанров с их уникальными идентификаторами
         * @summary Получить список жанров
         * @param {number} [page] Номер страницы
         * @param {number} [size] Количество элементов на странице (1-100)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listGenresApiV1GenresGet: async (page?: number, size?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/genres/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Возвращает информацию о персоне по его идентификатору
         * @summary Получить информацию о персоне
         * @param {string} personId UUID персоны
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        personDetailsApiV1PersonsPersonIdGet: async (personId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'personId' is not null or undefined
            assertParamExists('personDetailsApiV1PersonsPersonIdGet', 'personId', personId)
            const localVarPath = `/api/v1/persons/{person_id}`
                .replace(`{${"person_id"}}`, encodeURIComponent(String(personId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Полнотекстовый поиск по названиям и описаниям кинопроизведений
         * @summary Поиск кинопроизведений
         * @param {string} query Поисковый запрос
         * @param {number} [page] Номер страницы
         * @param {number} [size] Количество элементов
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchFilmsApiV1FilmsSearchGet: async (query: string, page?: number, size?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'query' is not null or undefined
            assertParamExists('searchFilmsApiV1FilmsSearchGet', 'query', query)
            const localVarPath = `/api/v1/films/search/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (query !== undefined) {
                localVarQueryParameter['query'] = query;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Полнотекстовый поиск персон по имени
         * @summary Поиск персон
         * @param {string} query Поисковый запрос
         * @param {number} [page] Номер страницы
         * @param {number} [size] Количество элементов
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchFilmsApiV1PersonsSearchGet: async (query: string, page?: number, size?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'query' is not null or undefined
            assertParamExists('searchFilmsApiV1PersonsSearchGet', 'query', query)
            const localVarPath = `/api/v1/persons/search/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (query !== undefined) {
                localVarQueryParameter['query'] = query;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * Возвращает полную информацию о кинопроизведении по его идентификатору
         * @summary Получить информацию о кинопроизведении
         * @param {string} filmId UUID фильма
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async filmDetailsApiV1FilmsFilmIdGet(filmId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FilmFullResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.filmDetailsApiV1FilmsFilmIdGet(filmId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.filmDetailsApiV1FilmsFilmIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Возвращает полную информацию о жанре по его идентификатору
         * @summary Получить информацию о жанре
         * @param {string} genreId UUID жанра
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async genreDetailsApiV1GenresGenreIdGet(genreId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Genre>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.genreDetailsApiV1GenresGenreIdGet(genreId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.genreDetailsApiV1GenresGenreIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Возвращает список из короткой информации по кинопроизведениям по заданным фильтрам
         * @summary Получить список фильмов по заданным критериям
         * @param {string} [sort] Сортировка (-imdb_rating для DESC, imdb_rating для ASC)
         * @param {string | null} [genre] UUID жанра для фильтрации
         * @param {number} [page] Номер страницы
         * @param {number} [size] Количество элементов на странице (1-100)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listFilmsApiV1FilmsGet(sort?: string, genre?: string | null, page?: number, size?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<FilmShortResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listFilmsApiV1FilmsGet(sort, genre, page, size, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.listFilmsApiV1FilmsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Возвращает список из короткой информации по кинопроизведениям персоны
         * @summary Получить список фильмов персоны
         * @param {string} personId UUID персоны
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listFilmsApiV1PersonsPersonIdFilmsGet(personId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<PersonFilms>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listFilmsApiV1PersonsPersonIdFilmsGet(personId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.listFilmsApiV1PersonsPersonIdFilmsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Возвращает список жанров с их уникальными идентификаторами
         * @summary Получить список жанров
         * @param {number} [page] Номер страницы
         * @param {number} [size] Количество элементов на странице (1-100)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listGenresApiV1GenresGet(page?: number, size?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Genre>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listGenresApiV1GenresGet(page, size, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.listGenresApiV1GenresGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Возвращает информацию о персоне по его идентификатору
         * @summary Получить информацию о персоне
         * @param {string} personId UUID персоны
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async personDetailsApiV1PersonsPersonIdGet(personId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PersonFullResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.personDetailsApiV1PersonsPersonIdGet(personId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.personDetailsApiV1PersonsPersonIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Полнотекстовый поиск по названиям и описаниям кинопроизведений
         * @summary Поиск кинопроизведений
         * @param {string} query Поисковый запрос
         * @param {number} [page] Номер страницы
         * @param {number} [size] Количество элементов
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async searchFilmsApiV1FilmsSearchGet(query: string, page?: number, size?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<FilmBaseResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.searchFilmsApiV1FilmsSearchGet(query, page, size, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.searchFilmsApiV1FilmsSearchGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Полнотекстовый поиск персон по имени
         * @summary Поиск персон
         * @param {string} query Поисковый запрос
         * @param {number} [page] Номер страницы
         * @param {number} [size] Количество элементов
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async searchFilmsApiV1PersonsSearchGet(query: string, page?: number, size?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<PersonFullResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.searchFilmsApiV1PersonsSearchGet(query, page, size, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.searchFilmsApiV1PersonsSearchGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * Возвращает полную информацию о кинопроизведении по его идентификатору
         * @summary Получить информацию о кинопроизведении
         * @param {string} filmId UUID фильма
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        filmDetailsApiV1FilmsFilmIdGet(filmId: string, options?: RawAxiosRequestConfig): AxiosPromise<FilmFullResponse> {
            return localVarFp.filmDetailsApiV1FilmsFilmIdGet(filmId, options).then((request) => request(axios, basePath));
        },
        /**
         * Возвращает полную информацию о жанре по его идентификатору
         * @summary Получить информацию о жанре
         * @param {string} genreId UUID жанра
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        genreDetailsApiV1GenresGenreIdGet(genreId: string, options?: RawAxiosRequestConfig): AxiosPromise<Genre> {
            return localVarFp.genreDetailsApiV1GenresGenreIdGet(genreId, options).then((request) => request(axios, basePath));
        },
        /**
         * Возвращает список из короткой информации по кинопроизведениям по заданным фильтрам
         * @summary Получить список фильмов по заданным критериям
         * @param {string} [sort] Сортировка (-imdb_rating для DESC, imdb_rating для ASC)
         * @param {string | null} [genre] UUID жанра для фильтрации
         * @param {number} [page] Номер страницы
         * @param {number} [size] Количество элементов на странице (1-100)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listFilmsApiV1FilmsGet(sort?: string, genre?: string | null, page?: number, size?: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<FilmShortResponse>> {
            return localVarFp.listFilmsApiV1FilmsGet(sort, genre, page, size, options).then((request) => request(axios, basePath));
        },
        /**
         * Возвращает список из короткой информации по кинопроизведениям персоны
         * @summary Получить список фильмов персоны
         * @param {string} personId UUID персоны
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listFilmsApiV1PersonsPersonIdFilmsGet(personId: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<PersonFilms>> {
            return localVarFp.listFilmsApiV1PersonsPersonIdFilmsGet(personId, options).then((request) => request(axios, basePath));
        },
        /**
         * Возвращает список жанров с их уникальными идентификаторами
         * @summary Получить список жанров
         * @param {number} [page] Номер страницы
         * @param {number} [size] Количество элементов на странице (1-100)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listGenresApiV1GenresGet(page?: number, size?: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<Genre>> {
            return localVarFp.listGenresApiV1GenresGet(page, size, options).then((request) => request(axios, basePath));
        },
        /**
         * Возвращает информацию о персоне по его идентификатору
         * @summary Получить информацию о персоне
         * @param {string} personId UUID персоны
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        personDetailsApiV1PersonsPersonIdGet(personId: string, options?: RawAxiosRequestConfig): AxiosPromise<PersonFullResponse> {
            return localVarFp.personDetailsApiV1PersonsPersonIdGet(personId, options).then((request) => request(axios, basePath));
        },
        /**
         * Полнотекстовый поиск по названиям и описаниям кинопроизведений
         * @summary Поиск кинопроизведений
         * @param {string} query Поисковый запрос
         * @param {number} [page] Номер страницы
         * @param {number} [size] Количество элементов
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchFilmsApiV1FilmsSearchGet(query: string, page?: number, size?: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<FilmBaseResponse>> {
            return localVarFp.searchFilmsApiV1FilmsSearchGet(query, page, size, options).then((request) => request(axios, basePath));
        },
        /**
         * Полнотекстовый поиск персон по имени
         * @summary Поиск персон
         * @param {string} query Поисковый запрос
         * @param {number} [page] Номер страницы
         * @param {number} [size] Количество элементов
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchFilmsApiV1PersonsSearchGet(query: string, page?: number, size?: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<PersonFullResponse>> {
            return localVarFp.searchFilmsApiV1PersonsSearchGet(query, page, size, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * Возвращает полную информацию о кинопроизведении по его идентификатору
     * @summary Получить информацию о кинопроизведении
     * @param {string} filmId UUID фильма
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public filmDetailsApiV1FilmsFilmIdGet(filmId: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).filmDetailsApiV1FilmsFilmIdGet(filmId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Возвращает полную информацию о жанре по его идентификатору
     * @summary Получить информацию о жанре
     * @param {string} genreId UUID жанра
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public genreDetailsApiV1GenresGenreIdGet(genreId: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).genreDetailsApiV1GenresGenreIdGet(genreId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Возвращает список из короткой информации по кинопроизведениям по заданным фильтрам
     * @summary Получить список фильмов по заданным критериям
     * @param {string} [sort] Сортировка (-imdb_rating для DESC, imdb_rating для ASC)
     * @param {string | null} [genre] UUID жанра для фильтрации
     * @param {number} [page] Номер страницы
     * @param {number} [size] Количество элементов на странице (1-100)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public listFilmsApiV1FilmsGet(sort?: string, genre?: string | null, page?: number, size?: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).listFilmsApiV1FilmsGet(sort, genre, page, size, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Возвращает список из короткой информации по кинопроизведениям персоны
     * @summary Получить список фильмов персоны
     * @param {string} personId UUID персоны
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public listFilmsApiV1PersonsPersonIdFilmsGet(personId: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).listFilmsApiV1PersonsPersonIdFilmsGet(personId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Возвращает список жанров с их уникальными идентификаторами
     * @summary Получить список жанров
     * @param {number} [page] Номер страницы
     * @param {number} [size] Количество элементов на странице (1-100)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public listGenresApiV1GenresGet(page?: number, size?: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).listGenresApiV1GenresGet(page, size, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Возвращает информацию о персоне по его идентификатору
     * @summary Получить информацию о персоне
     * @param {string} personId UUID персоны
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public personDetailsApiV1PersonsPersonIdGet(personId: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).personDetailsApiV1PersonsPersonIdGet(personId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Полнотекстовый поиск по названиям и описаниям кинопроизведений
     * @summary Поиск кинопроизведений
     * @param {string} query Поисковый запрос
     * @param {number} [page] Номер страницы
     * @param {number} [size] Количество элементов
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public searchFilmsApiV1FilmsSearchGet(query: string, page?: number, size?: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).searchFilmsApiV1FilmsSearchGet(query, page, size, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Полнотекстовый поиск персон по имени
     * @summary Поиск персон
     * @param {string} query Поисковый запрос
     * @param {number} [page] Номер страницы
     * @param {number} [size] Количество элементов
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public searchFilmsApiV1PersonsSearchGet(query: string, page?: number, size?: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).searchFilmsApiV1PersonsSearchGet(query, page, size, options).then((request) => request(this.axios, this.basePath));
    }
}



